### ISSUE TITLE
BigGAN: fix flood loss

### ISSUE THREAD

**Issue by gwern** [tensorfork/tensorfork#9]
Flood loss reverses any loss below a set magnitude, turning gradient descent into gradient ascent and preventing loss from ever reaching 0. In theory, this should be quite useful for GANs, by automatically stopping a runaway G/D from beating its counterpart: if it gets *too* good it will be actively worsened by the flood loss until such time as the other half can catch up and it stops being too good. 

We have found it to be helpful in stabilizing BigGAN, yielding characteristic 'bounces' in the loss curves when one half gets too good, but on a few occasions, BigGAN has nevertheless collapsed to exactly 0 loss in either G or D - sometimes immediately on initialization (as far as our sparse every-_n_ iterations logging can tell). 

This seems like a bug. It may be mathematically possible for a model to hit zero loss after doing a gradient ascent step (perhaps either that other point is equivalent or better, by chance, or the other half did a bad gradient descent step and immediately caused it to have a zero loss regardless), but it seems a lot less likely than a bug in the implementation.

Could the steps be happening before the flood loss? Are there other gradient descent steps at play?

**Comment by shawwn** [comment]
Turns out that tensorboard was logging the incorrect scalar value. Flood loss was likely working properly.

Will reopen this if the problem pops up again.
